### ISSUE TITLE
Performance impact

### ISSUE THREAD

**Issue by bluprince13** [Treora/redux-query-sync#31] opened 2018-12-28 09:31 UTC
I found that using redux-query-sync with a range input was resulting in quite a bit of lag when using the slider. Any advice on how to address this or reduce the performance impact?

**Comment by bluprince13** [comment] 2018-12-28 09:48
Setting `options.initialTruth` to `store` rather than `location` made it a little bit faster.

**Comment by Treora** [comment] 2018-12-31 16:20
I can imagine that a rapid sequence of updates, as is easily produced by dragging a range input, could be a little slow. My first guess is that the issue is in the browser expecting the URL to not change so quickly, or perhaps the URL change is triggering other processing each time. But this is just guessing, I have not profiled this module's performance.

One thing that could help is throttling the input event handler, to have it run at most once per, say, 100ms. Try for example the [throttle](https://lodash.com/docs/#throttle) function of lodash.

> Setting `options.initialTruth` to `store` rather than `location` made it a little bit faster.

This surprises me, as this option should only influence the initial run of `ReduxQuerySync`. Might you accidentally be initialising the whole thing (i.e. calling `ReduxQuerySync...`) every time the slider is moved?

**Comment by bluprince13** [comment] 2018-12-31 16:27
Thanks for your reply. I haven't got a MWE, but the app that I'm working on is [here](https://renting-vs-buying-house.netlify.com).

That's a good idea on throttling the input. I'll try that :)

> This surprises me, as this option should only influence the initial run of ReduxQuerySync. Might you accidentally be initialising the whole thing (i.e. calling ReduxQuerySync...) every time the slider is moved?

Now that you say that, it's possible I just imagined it was going faster :P 

Thanks for creating this tool anyway. Very handy and easy to implement :)

**Comment by Treora** [comment] 2019-04-11 11:04
Closing as throttling state changes seems a reasonable solution. Can be reopened if needed.

**Closed as completed by Treora** 2019-04-11 11:04 UTC

**Comment by bluprince13** [comment] 2019-04-26 15:45
@Treora I tried using a throttle (specifically [lodash's throttle](https://lodash.com/docs/4.17.11#throttle)). However, the performance still isn't satisfactory.

If I disable redux-query-sync, my performance issue goes away. 

Is it possible to debounce the url update? For example, say I'm using a slider on a range input to change the state of a variable. While I'm dragging the slider, the state changes and the UI updates happen etc. However, the URL only updates once I've stopped dragging the slider?

**Comment by Treora** [comment] 2019-04-26 17:16
> Is it possible to debounce the url update?

I don't think so.. I'm pondering whether you could do some trick by using `throttle` on the `selector` callback, so it would return an outdated state instead of the current one and hence not trigger a URL update. This might actually work, but it could leave the URL with a slightly outdated parameter (throttle's trailing edge won't help because, although will invoke your selector, the result will not be used).

> However, the URL only updates once I've stopped dragging the slider?

Another approach that pops up: perhaps you could have two variables in the state, the first one being synced to the URL, and synced by the second variable (the current slider state) upon an action 'sliderReleased'. So the `selector` would read the first variable; but I suppose the `action` would update the second variable. However this seems a bit complex and I have not thought this through, it might actually reset the first variable again with the parameter read from the URL, either directly or if for some reason the URL changes, creating weird behaviour.

Just quickly providing inspiration here, I hope it helps. I would still first try figure out what actually causes the performance issue. It could be that you would be better off with another approach than the instant syncing this module tries to achieve.
