### ISSUE TITLE
Please Add some Demo Example

### ISSUE THREAD

**Issue by devtanuj** [Treora/redux-query-sync#34] opened 2019-05-05 13:02 UTC
Please Provide some Demo Examples.

**Comment by Treora** [comment] 2019-05-07 13:05
Duplicate of #21. I just noticed somebody already shared a working example in that thread, which is now linked to from the readme. I hope that helps you.

**Closed as completed by Treora** 2019-05-07 13:05 UTC

**Comment by devtanuj** [comment] 2019-05-08 02:05
@Treora 

thanks but I'm looking for the example where we can dispatch async actions along with query sync.
